#!/usr/bin/env sh

yabai -m config layout bsp

yabai -m rule --add app="^System Settings$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Mullvad$" sticky=on layer=above manage=off
yabai -m rule --add app="^Swish" sticky=on layer=above manage=off
yabai -m rule --add app="^Multitouch" sticky=on layer=above manage=off
yabai -m rule --add app="^Hyperkey" sticky=on layer=above manage=off

# yabai -m config focus_follows_mouse autoraise
yabai -m config focus_follows_mouse on
yabai -m config mouse_follows_focus on

yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config active_window_border_color 0xFFFFFFFF
yabai -m config normal_window_border_color 0x00FFFFFF
yabai -m config insert_feedback_color      0xFF00FF00

yabai -m config auto_balance off
yabai -m config split_ratio 0.5
yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m config layout bsp
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 4

echo "Yabai configuration loaded."